name: Beta Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 8
          check-latest: true
      - name: Set version
        run: echo "VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk8
          arguments: build --no-build-cache
          gradle-version: wrapper
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Raven-B+++
          path: build/libs/RavenB+++-1.12.2.jar
